"""Test

Revision ID: 7a9c9dc0bd14
Revises: b2544ed46390
Create Date: 2025-07-28 07:23:03.771814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a9c9dc0bd14'
down_revision = 'b2544ed46390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('block_type', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
